apiVersion: batch/v1
kind: Job
metadata:
  name: "{{._NAME_}}"
  namespace: {{.namespace}}
spec:
  completions: {{.replicas}}
  parallelism: {{.replicas}}
  template:
    metadata:
      labels:
        applicationId: {{._NAME_}}
        queue: {{.queue}}
        app: {{._NAME_}}
      annotations:
        pod-complete.stage.kwok.x-k8s.io/delay: "{{.ttl}}"
        pod-complete.stage.kwok.x-k8s.io/jitter-delay: "{{.ttl}}"
    spec:
      schedulerName: yunikorn
      nodeSelector:
        type: kwok
      containers:
      - name: test
        image: {{.image}}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: {{.cpu}}
            memory: {{.memory}}
            {{- if .gpu }}
            nvidia.com/gpu: {{.gpu}}
            {{- end }}
          requests:
            cpu: {{.cpu}}
            memory: {{.memory}}
            {{- if .gpu }}
            nvidia.com/gpu: {{.gpu}}
            {{- end }}
      restartPolicy: Never
