apiVersion: batch/v1
kind: Job
metadata:
  name: "{{._NAME_}}"
  namespace: {{.namespace}}
spec:
  completions: {{.replicas}}
  parallelism: {{.replicas}}
  template:
    metadata:
      labels:
        applicationId: "test-{{._NAME_}}"
        app: "test-{{._NAME_}}"
        queue: {{.queue}}
      annotations:
        pod-complete.stage.kwok.x-k8s.io/delay: "{{.ttl}}"
    spec:
      schedulerName: yunikorn
      containers:
      - name: test
        image: ubuntu
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: {{.cpu}}
            memory: {{.memory}}
            {{- if .gpu }}
            nvidia.com/gpu: {{.gpu}}
            {{- end }}
          requests:
            cpu: {{.cpu}}
            memory: {{.memory}}
            {{- if .gpu }}
            nvidia.com/gpu: {{.gpu}}
            {{- end }}
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - "kwok"
      tolerations:
      - key: "kwok.x-k8s.io/node"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        "type": kwok
