# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: config-kueue-topology-aware
description: configure Kueue for network topology awareness testing
tasks:
- id: register-cluster-queue
  type: RegisterObj
  params:
    template: "resources/templates/kueue/cluster-queue.yaml"
- id: register-local-queue
  type: RegisterObj
  params:
    template: "resources/templates/kueue/local-queue.yaml"
- id: register-resource-flavor
  type: RegisterObj
  params:
    template: "resources/templates/kueue/resource-flavor.yaml"
- id: register-job
  type: RegisterObj
  params:
    template: "resources/benchmarks/topology-aware/templates/kueue/job.yaml"
    nameFormat: "topo-job{{._ENUM_}}"
    podNameFormat: "{{._NAME_}}-[0-9]-.*"
    podCount: "{{.parallelism}}"
- id: create-resource-flavor
  type: SubmitObj
  params:
    refTaskId: register-resource-flavor
    canExist: true
    params:
      name: "net-optimal-nodes"
      nodeLabels:
        net-optimal: "true"
- id: create-resource-flavor-general
  type: SubmitObj
  params:
    refTaskId: register-resource-flavor
    canExist: true
    params:
      name: "gpu-node"
      nodeLabels:
        nvidia.com/gpu.count: "8"
- id: create-cluster-queue
  type: SubmitObj
  params:
    refTaskId: register-cluster-queue
    canExist: true
    params:
      name: nwtopo-queue
      flavor: gpu-node
      cpu: 8
      memory: 36Gi
      pods: 12
      gpu: 96
- id: create-local-queue
  type: SubmitObj
  params:
    refTaskId: register-local-queue
    canExist: true
    params:
      name: nwtopo-local-queue
      namespace: default
      clusterQueue: nwtopo-queue
- id: configure
  type: Configure
  params:
    configmaps:
    - name: kueue-manager-config
      namespace: kueue-system
      op: create
      data:
        controller_manager_config.yaml: |
          apiVersion: config.kueue.x-k8s.io/v1beta1
          kind: Configuration
          health:
            healthProbeBindAddress: :8081
          metrics:
            bindAddress: :8080
          webhook:
            port: 9443
          leaderElection:
            leaderElect: true
            resourceName: c1f6bfd2.kueue.x-k8s.io
          controller:
            groupKindConcurrency:
              Job.batch: 5
              Pod: 5
              Workload.kueue.x-k8s.io: 5
              LocalQueue.kueue.x-k8s.io: 1
              ClusterQueue.kueue.x-k8s.io: 1
              ResourceFlavor.kueue.x-k8s.io: 1
          clientConnection:
            qps: 50
            burst: 100
          waitForPodsReady:
            enable: true
            timeout: 5m
            blockAdmission: true
            requeuingStrategy:
              timestamp: Eviction
              backoffLimitCount: null
              backoffBaseSeconds: 60
              backoffMaxSeconds: 3600
          integrations:
            frameworks:
            - "batch/job"
            - "kubeflow.org/mpijob"
            - "ray.io/rayjob"
            - "ray.io/raycluster"
            - "jobset.x-k8s.io/jobset"
            - "kubeflow.org/mxjob"
            - "kubeflow.org/paddlejob"
            - "kubeflow.org/pytorchjob"
            - "kubeflow.org/tfjob"
            - "kubeflow.org/xgboostjob"
    deploymentRestarts:
    - namespace: kueue-system
      name: kueue-controller-manager
    timeout: 1m