apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: "{{._NAME_}}"
  namespace: "{{.namespace}}"
spec:
  minAvailable: {{.minAvailable}}
  schedulerName: volcano
  priorityClassName: {{.priorityClassName}}
  policies:
  - event: PodEvicted
    action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
  - replicas: {{.replicas}}
    name: test
    template:
      metadata:
        name: test
        annotations:
          {{- if .ttl }}
          pod-complete.stage.kwok.x-k8s.io/delay: "{{.ttl}}"
          pod-complete.stage.kwok.x-k8s.io/jitter-delay: "{{.ttl}}"
          {{- end }}
      spec:
        containers:
        - name: job
          image: {{.image}}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "{{.cpu}}"
              memory: {{.memory}}
              nvidia.com/gpu: "{{.gpu}}"
            requests:
              cpu: "{{.cpu}}"
              memory: {{.memory}}
      restartPolicy: OnFailure
