apiVersion: batch/v1
kind: Job
metadata:
  name: "{{._NAME_}}"
  namespace: {{.namespace}}
  labels:
    kueue.x-k8s.io/queue-name: {{.queueName}}
    {{- if .priority }}
    kueue.x-k8s.io/priority-class: {{.priority}}
    {{- end }}
spec:
  suspend: true
  completions: {{.replicas}}
  parallelism: {{.replicas}}
  completionMode: {{.completionMode}}
  template:
    metadata:
      annotations:
        {{- if .ttl }}
        pod-complete.stage.kwok.x-k8s.io/delay: "{{.ttl}}"
        pod-complete.stage.kwok.x-k8s.io/jitter-delay: "{{.ttl}}"
        {{- end }}
    spec:
      containers:
      - name: test
        image: ubuntu
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "{{.cpu}}"
            memory: {{.memory}}
            {{- if .gpu }}
            nvidia.com/gpu: "{{.gpu}}"
            {{- end }}
          requests:
            cpu: "{{.cpu}}"
            memory: {{.memory}}
            {{- if .gpu }}
            nvidia.com/gpu: "{{.gpu}}"
            {{- end }}
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - "kwok"
      tolerations:
      - key: "kwok.x-k8s.io/node"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        "type": kwok
