apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: unified-job-exporter-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: unified-job-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 10s
