apiVersion: v1
kind: ServiceAccount
metadata:
  name: unified-job-exporter
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unified-job-exporter-reader
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch.volcano.sh"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unified-job-exporter-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unified-job-exporter-reader
subjects:
  - kind: ServiceAccount
    name: unified-job-exporter
    namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unified-job-exporter
  namespace: monitoring
  labels:
    app: unified-job-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unified-job-exporter
  template:
    metadata:
      labels:
        app: unified-job-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: unified-job-exporter
      containers:
        - name: exporter
          image: mateuszskowron21/metrics-exporter:v1.14
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http-metrics
          env:
            - name: LISTEN_PORT
              value: "8000"
            - name: SCRAPE_INTERVAL
              value: "15"
            - name: LOG_LEVEL
              value: "DEBUG"
          resources:
            requests:
              cpu: 1000m
              memory: 1024Mi
            limits:
              cpu: 1500m
              memory: 2048Mi
---
apiVersion: v1
kind: Service
metadata:
  name: unified-job-exporter-service
  namespace: monitoring
  labels:
    app: unified-job-exporter
spec:
  selector:
    app: unified-job-exporter
  ports:
    - name: http-metrics
      port: 8000
      targetPort: http-metrics
