apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-resource-exporter # Zmieniona nazwa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-resource-exporter-reader # Zmieniona nazwa
rules:
  - apiGroups: [""] # Core API group
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list"]
  - apiGroups: ["batch.volcano.sh"]
    resources: ["jobs"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-resource-exporter-binding # Zmieniona nazwa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-resource-exporter-reader # Zmieniona nazwa
subjects:
  - kind: ServiceAccount
    name: node-resource-exporter # Zmieniona nazwa
    namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-resource-exporter # Zmieniona nazwa
  namespace: monitoring
  labels:
    app: node-resource-exporter # Zmieniona etykieta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-resource-exporter # Zmieniona etykieta
  template:
    metadata:
      labels:
        app: node-resource-exporter # Zmieniona etykieta
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001" # Inny port
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: node-resource-exporter # Zmieniona nazwa
      containers:
        - name: exporter
          image: mateuszskowron21/node-resource-exporter:v1.12
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              name: http-metrics
          env:
            - name: LISTEN_PORT
              value: "8001"
            - name: SCRAPE_INTERVAL
              value: "10"
            - name: LOG_LEVEL
              value: "INFO"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
---
apiVersion: v1
kind: Service
metadata:
  name: node-resource-exporter-service # Zmieniona nazwa
  namespace: monitoring
  labels:
    app: node-resource-exporter # Zmieniona etykieta
spec:
  selector:
    app: node-resource-exporter # Zmieniona etykieta
  ports:
    - name: http-metrics
      port: 8001 # Inny port
      targetPort: http-metrics
