apiVersion: batch/v1
kind: Job
metadata:
  name: "{{._NAME_}}"
  namespace: {{.namespace}}
  labels:
    kueue.x-k8s.io/queue-name: {{.queueName}}
spec:
  suspend: true
  completions: {{.replicas}}
  parallelism: {{.replicas}}
  completionMode: {{.completionMode}}
  template:
    metadata:
      annotations:
        pod-complete.stage.kwok.x-k8s.io/delay: {{.ttl}}
        pod-complete.stage.kwok.x-k8s.io/jitter-delay: {{.ttl}}
        {{- if eq .topologyType "preferred" }}
        kueue.x-k8s.io/podset-preferred-topology: {{.topologyLevel}}
        {{- else if eq .topologyType "required" }}
        kueue.x-k8s.io/podset-required-topology: {{.topologyLevel}}
        {{- end }}
    spec:
      schedulerName: default-scheduler
      containers:
      - name: test
        image: {{.image}}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: {{.cpu}}
            memory: {{.memory}}
            nvidia.com/gpu: {{.gpu}}
          requests:
            cpu: {{.cpu}}
            memory: {{.memory}}
            nvidia.com/gpu: {{.gpu}}
      restartPolicy: Never
